### ISSUE TITLE
Make compatible with React Native?

### ISSUE THREAD

**Issue by marksyzm** [dfcreative/audio-format#7]
Everything seems to excellent for this, but I'm going to have to fork this and `audio-format` in order to create a failsafe or alternative to switch to `Platform.OS` which react native uses. Would you consider implementing this? 

Otherwise I'm happy to fork and send a PR if time/work is of the essence

**Comment by dy** [comment]
Hi @marksyzm! Not sure I understood your proposal but of course you're free to fork and propose a PR!
